version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend  
      dockerfile: Dockerfile    
    ports:
      - "8080:80"

  backend:
    build:
      context: ./src/backend  
      dockerfile: Dockerfile    
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hades
      POSTGRES_DB: fullstack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  pgdata:
